from typing import Any


DISCLAIMER = (
    "This application is a diabetes risk support tool. It provides an estimated risk probability "
    "based on structured health information and should not be used as a medical diagnosis."
)


FEATURE_SCHEMA: list[dict[str, Any]] = [
    {
        "key": "age",
        "label": "Age",
        "type": "integer",
        "required": True,
        "step": 1,
        "section": "basic",
        "min": 18,
        "max": 120,
        "description": "Age in years.",
    },
    {
        "key": "sex",
        "label": "Sex",
        "type": "string",
        "required": True,
        "step": 1,
        "section": "basic",
        "options": ["female", "male", "other"],
        "description": "Biological sex used for intake context.",
    },
    {
        "key": "family_history_diabetes",
        "label": "Family history of diabetes",
        "type": "boolean",
        "required": True,
        "step": 1,
        "section": "basic",
        "description": "Whether a close family member has diabetes.",
    },
    {
        "key": "smoking",
        "label": "Smoking",
        "type": "boolean",
        "required": True,
        "step": 1,
        "section": "basic",
        "description": "Current smoking status.",
    },
    {
        "key": "height_cm",
        "label": "Height (cm)",
        "type": "number",
        "required": True,
        "step": 2,
        "section": "body_metrics",
        "min": 100,
        "max": 250,
        "description": "Height in centimeters.",
    },
    {
        "key": "weight_kg",
        "label": "Weight (kg)",
        "type": "number",
        "required": True,
        "step": 2,
        "section": "body_metrics",
        "min": 20,
        "max": 350,
        "description": "Weight in kilograms.",
    },
    {
        "key": "bmi",
        "label": "BMI",
        "type": "number",
        "required": False,
        "step": 2,
        "section": "body_metrics",
        "min": 10,
        "max": 80,
        "description": "Auto-calculated from height and weight when available.",
    },
    {
        "key": "systolic_bp",
        "label": "Systolic blood pressure",
        "type": "integer",
        "required": True,
        "step": 2,
        "section": "vitals",
        "min": 70,
        "max": 250,
        "description": "Systolic blood pressure in mmHg.",
    },
    {
        "key": "diastolic_bp",
        "label": "Diastolic blood pressure",
        "type": "integer",
        "required": True,
        "step": 2,
        "section": "vitals",
        "min": 40,
        "max": 150,
        "description": "Diastolic blood pressure in mmHg.",
    },
    {
        "key": "heart_rate",
        "label": "Heart rate",
        "type": "integer",
        "required": False,
        "step": 2,
        "section": "vitals",
        "min": 30,
        "max": 220,
        "description": "Optional resting heart rate in beats per minute.",
    },
    {
        "key": "physical_activity_days_per_week",
        "label": "Physical activity per week",
        "type": "integer",
        "required": True,
        "step": 2,
        "section": "lifestyle",
        "min": 0,
        "max": 7,
        "description": "Days per week with meaningful physical activity.",
    },
    {
        "key": "hypertension",
        "label": "Hypertension",
        "type": "boolean",
        "required": True,
        "step": 3,
        "section": "conditions",
        "description": "Known hypertension diagnosis.",
    },
    {
        "key": "cardiovascular_disease",
        "label": "Cardiovascular disease",
        "type": "boolean",
        "required": True,
        "step": 3,
        "section": "conditions",
        "description": "Known cardiovascular disease history.",
    },
    {
        "key": "stroke_history",
        "label": "Stroke history",
        "type": "boolean",
        "required": True,
        "step": 3,
        "section": "conditions",
        "description": "Prior stroke history.",
    },
    {
        "key": "pregnancy_count",
        "label": "Pregnancy count",
        "type": "integer",
        "required": False,
        "step": 3,
        "section": "conditions",
        "min": 0,
        "max": 20,
        "description": "Optional prior pregnancy count if applicable.",
    },
    {
        "key": "fasting_glucose_mg_dl",
        "label": "Fasting glucose (mg/dL)",
        "type": "number",
        "required": False,
        "step": 4,
        "section": "labs",
        "min": 40,
        "max": 500,
        "improves_accuracy": True,
        "description": "Optional fasting glucose in mg/dL.",
    },
    {
        "key": "fasting_glucose_mmol_l",
        "label": "Fasting glucose (mmol/L)",
        "type": "number",
        "required": False,
        "step": 4,
        "section": "labs",
        "min": 2,
        "max": 30,
        "improves_accuracy": True,
        "description": "Optional fasting glucose in mmol/L.",
    },
    {
        "key": "hba1c",
        "label": "HbA1c (%)",
        "type": "number",
        "required": False,
        "step": 4,
        "section": "labs",
        "min": 3,
        "max": 20,
        "improves_accuracy": True,
        "description": "Optional glycated hemoglobin value.",
    },
    {
        "key": "insulin",
        "label": "Insulin (uIU/mL)",
        "type": "number",
        "required": False,
        "step": 4,
        "section": "labs",
        "min": 0,
        "max": 1000,
        "improves_accuracy": True,
        "description": "Optional fasting insulin value.",
    },
    {
        "key": "homa_ir",
        "label": "HOMA-IR",
        "type": "number",
        "required": False,
        "step": 4,
        "section": "labs",
        "min": 0,
        "max": 30,
        "improves_accuracy": True,
        "description": "Optional insulin resistance metric.",
    },
    {
        "key": "cholesterol_total",
        "label": "Total cholesterol (mg/dL)",
        "type": "number",
        "required": False,
        "step": 4,
        "section": "labs",
        "min": 50,
        "max": 500,
        "improves_accuracy": True,
        "description": "Optional total cholesterol value.",
    },
]


REQUIRED_INPUT_KEYS = [field["key"] for field in FEATURE_SCHEMA if field.get("required")]
OPTIONAL_LAB_KEYS = [
    field["key"]
    for field in FEATURE_SCHEMA
    if field.get("section") == "labs"
]
